trigger:
- main

resources:
- repo: self

stages:
- stage: BuildandpublishtoACR
  displayName: Build and publish to ACR

  jobs:
  - job: Build
    displayName: Build project
    pool:
      name: default
      vmImage: myVM

    steps:
    - task: Docker@2
      displayName: Build docker Image
      inputs:
        containerRegistry: 'POCcontainerdtmt'
        repository: 'JavaPOCImage/provider'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
